apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: xserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xserver
    spec:
      containers:
      - name: xserver
        image: dmitrytsydenov/xserver:v0.1.1
        ports:
        - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: xserver
spec:
  type: LoadBalancer
  ports:
  - port: 1337
  selector:
    app: xserver